/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * My AR Project API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 花火を作成するためのリクエストボディ
 */
export interface FireworkCreateRequest {
	/** 花火が共有可能かどうか */
	isShareable: boolean;
	/** 花火の元となる画像ファイル */
	image: Blob;
}
