/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * My AR Project API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 花火のレスポンスデータ
 */
export interface FireworkResponse {
	/** 花火のID */
	id: number;
	/** 花火が共有可能かどうか */
	isShareable: boolean;
	/** 花火のピクセルデータ */
	pixelData: boolean[];
	/** 花火の作成日時 */
	createdAt?: string;
	/** 花火の更新日時 */
	updatedAt?: string;
}
