# version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.backend.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=slackdb
  #     - SLACK_API_TOKEN_BOT=${SLACK_API_TOKEN_BOT}
  #     - SLACK_API_TOKEN_USER=${SLACK_API_TOKEN_USER}


  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.frontend.dev
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev


volumes:
  db_data: